apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: bookstack
  name: bookstack
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: '172.30.1.1:5000/bookstack/bookstack'
  tags:
    - items:
      tag: latest
