apiVersion: v1
kind: Template
metadata:
  name: bookstack
objects:
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: "bookstack-db"
  spec:
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: "1Gi"
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: "bookstack-storage"
  spec:
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: "1Gi"
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: "bookstack-uploads"
  spec:
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: "1Gi"
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: bookstack
      template: bookstack
    name: bookstack-db
  spec:
    replicas: 1
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: bookstack-db
      spec:
        containers:
          - image: registry.access.redhat.com/rhscl/mysql-57-rhel7
            imagePullPolicy: IfNotPresent
            name: bookstack-db
            ports:
              - containerPort: 3306
                protocol: TCP
            env:
              - name: MYSQL_ROOT_PASSWORD
                value: secret
              - name: MYSQL_DATABASE
                value: bookstack
              - name: MYSQL_USER
                value: bookstack
              - name: MYSQL_PASSWORD
                value: secret
            volumeMounts:
              - mountPath: /var/lib/mysql
                name: bookstack-db
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
          - name: bookstack-db
            persistentVolumeClaim:
              claimName: bookstack-db
    triggers:
      - type: ConfigChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: bookstack
    name: bookstack
  spec:
    replicas: 1
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: bookstack
      spec:
        containers:
          - image: pacroy/bookstack-openshift:1.0.0
            imagePullPolicy: Always
            name: bookstack
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: DB_HOST
                value: bookstack-db:3306
              - name: DB_DATABASE
                value: bookstack
              - name: DB_USERNAME
                value: bookstack
              - name: DB_PASSWORD
                value: secret
            volumeMounts:
              - mountPath: /var/www/bookstack/public/storage
                name: bookstack-storage
              - mountPath: /var/www/bookstack/public/uploads
                name: bookstack-uploads
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
          - name: bookstack-storage
            persistentVolumeClaim:
              claimName: bookstack-storage
          - name: bookstack-uploads
            persistentVolumeClaim:
              claimName: bookstack-uploads
    triggers:
      - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: bookstack
      template: bookstack
    name: bookstack-db 
  spec:
    selector:                  
      deploymentconfig: bookstack-db
    ports:
    - name: 3306-tcp
      port: 3306               
      protocol: TCP
      targetPort: 3306
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: bookstack
      template: bookstack
    name: bookstack
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      deploymentconfig: bookstack
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: bookstack
      template: bookstack
    name: bookstack
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: bookstack
      weight: 100
    wildcardPolicy: None

